### PR TITLE
Support order_result API call

### PR DESCRIPTION
**Pull request by jamescook**

### CODE REVIEW

**Comment by knewter** [comment]
@sferik I looked at this and it looks pleasant.  :+1:

**Comment by sferik** [comment]
This looks good to me as well.

@jamescook Would you mind rebasing your branch against the latest `master` so it merges cleanly?

**Comment by jamescook** [comment]
Done

**Comment by sferik** [comment]
Apparently, this is causing the build to fail. Can you please look into why.

**Comment by jamescook** [comment]
@sferik how 'bout now?

**Comment by sferik** [comment]
Looks good! Thanks.

**Pull request merged**
