### PR TITLE
mtgox declines API calls to mtgox.com

### PR DESCRIPTION
**Pull request by thams**
this replaces use of mtgox.com with data.mtgox.com

### CODE REVIEW

**Comment by sferik** [comment]
According to [this announcement](https://bitcointalk.org/index.php?topic=150786.0), this new hostname is only for unauthenticated requests. This will fix calls to the ticker, depth, and history but I believe it will break trades and other authenticated requests.

**Comment by thams** [comment]
From experimentation, I observe that data.mtgox.com supports authenticated as well as unauthenticated requests, though from the announcement you quoted, I suspect that mtgox.com may be faster when servicing authenticated requests.

**Comment by thams** [comment]
Unclear how to proceed. MtGox::Connection#connection sets the URL for the API, but it doesn't have enough information to safely dispatch mtgox.com or data.mtgox.com. It is conveniently true (for the moment) that MtGox API uses GET for all unauthenticated calls, and POST for authenticated ones. Would be a hack to decide based on that.

**Comment by yrral86** [comment]
I still need to clean it up, but here is what I'm using:
https://github.com/yrral86/mtgox/commit/9d8d7afed2494c58dddb7c874151e48dd6cf1914

Be warned, my master branch has ssl verification disabled because mtgox let their certificate expire tonight.

**Comment by elthariel** [comment]
Despite their statement, even the ticker doens't work when you aren't using data.mtgox.com

**Comment by thams** [comment]
Yeah, my bad for pushing it to the original pull branch as I was rushing out the door. Meant to provide it as a starting point for someone else on the thread who was having problems.

**Comment by sferik** [comment]
Closed by #29.

**Pull request closed without merging**
